name: "test"

on:
  push:
    branches:
      - main
      - topic/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm build
      - uses: ./packages/example
      - uses: ./packages/sample
